### PR TITLE
command-not-found support for homebrew (linuxbrew)

### LINKED ISSUE #1: [feature] Support homebrew (linuxbrew)
According to <https://docs.brew.sh/Manpage#command-not-found-init>
```shell
HB_CNF_HANDLER="$HOMEBREW_PREFIX/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
  source "$HB_CNF_HANDLER"
fi
```

`$HOMEBREW_PREFIX` is different in various OS and machines (macOS for x86, macOS for arm, linux). I recommend to add some tips in README.md to tell user to set it according to <https://docs.brew.sh/Manpage#shellenv>.

### PR DESCRIPTION
**Pull request by Freed-Wu**
Fix #1

### CODE REVIEW

**Comment by Tarrasch** [comment]
@Freed-Wu is this what the oh-my-zsh plugin already does?

**Comment by Freed-Wu** [comment]
Yet not, should I notify them of this PR?

**Comment by Tarrasch** [comment]
@Freed-Wu I think this repository should just be in sync with what oh-my-zsh have.

**Comment by Freed-Wu** [comment]
Okay, let me ask ohmyzsh for adding support for homebrew.

**Comment by Freed-Wu** [comment]
I notice this plugin is older than ohmyzsh. Does it need a update?

<https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/command-not-found/command-not-found.plugin.zsh>

**Pull request closed without merging**
